<a href="https://colab.research.google.com/github/geokoshy89/colab_rest_api/blob/master/pytorch_create_save.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

In [5]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [6]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [13]:
X= dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20, random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
Xtrain_=torch.from_numpy(X_train).float()
Xtest_=torch.from_numpy(X_test).float()

In [17]:
Xtrain_

tensor([[-0.0935,  0.2215],
        [ 1.2217, -0.5342],
        [-1.0655,  0.4104],
        ...,
        [ 1.2789,  0.4104],
        [-0.9512,  0.2215],
        [-1.2943, -1.4316]])

In [31]:
ytrain_=torch.from_numpy(y_train)
ytest_=torch.from_numpy(y_test)

In [32]:
ytrain_

tensor([1, 1, 1,  ..., 1, 1, 0])

In [20]:
Xtrain_.shape,ytrain_.shape

(torch.Size([1243, 2]), torch.Size([1243]))

In [21]:
Xtest_.shape,ytest_.shape

(torch.Size([311, 2]), torch.Size([311]))

In [22]:
input_size=2
output_size=2
hidden_size=10

In [26]:
class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    self.fc1= torch.nn.Linear(input_size,hidden_size)
    self.fc2= torch.nn.Linear(hidden_size,hidden_size)
    self.fc3= torch.nn.Linear(hidden_size,output_size)

  def forward(self,X):
    X=torch.relu(self.fc1(X))
    X=torch.relu(self.fc2(X))
    X= self.fc3(X)
    
    return F.log_softmax(X,dim=1)

In [27]:
model= Net()

In [28]:
import torch.optim as optim
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)
loss_fn=nn.NLLLoss()

In [29]:
epochs=100

In [33]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred=model(Xtrain_)
  loss=loss_fn(Ypred,ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch,'Loss',loss.item())

Epoch 0 Loss 0.7221760749816895
Epoch 1 Loss 0.6892404556274414
Epoch 2 Loss 0.6606497168540955
Epoch 3 Loss 0.6350910067558289
Epoch 4 Loss 0.6127482652664185
Epoch 5 Loss 0.5920902490615845
Epoch 6 Loss 0.572117805480957
Epoch 7 Loss 0.5528181195259094
Epoch 8 Loss 0.5331220626831055
Epoch 9 Loss 0.5128406882286072
Epoch 10 Loss 0.4919619560241699
Epoch 11 Loss 0.4704231321811676
Epoch 12 Loss 0.44821420311927795
Epoch 13 Loss 0.42553088068962097
Epoch 14 Loss 0.40298017859458923
Epoch 15 Loss 0.3810177445411682
Epoch 16 Loss 0.35938483476638794
Epoch 17 Loss 0.337996244430542
Epoch 18 Loss 0.31752723455429077
Epoch 19 Loss 0.2977794408798218
Epoch 20 Loss 0.27914556860923767
Epoch 21 Loss 0.2619365453720093
Epoch 22 Loss 0.24598835408687592
Epoch 23 Loss 0.23125268518924713
Epoch 24 Loss 0.21772560477256775
Epoch 25 Loss 0.20551009476184845
Epoch 26 Loss 0.19446530938148499
Epoch 27 Loss 0.18455682694911957
Epoch 28 Loss 0.175722137093544
Epoch 29 Loss 0.1678672581911087
Epoch 30 Lo

In [35]:
list(model.parameters())

[Parameter containing:
 tensor([[ 1.0988, -0.1193],
         [-0.0057, -0.2760],
         [ 0.5741, -0.5408],
         [-0.6625,  0.7003],
         [-0.5312,  0.5740],
         [-0.7026,  0.1856],
         [-0.5304, -0.5804],
         [-0.6738, -0.7524],
         [-0.7640, -0.5853],
         [-0.3940, -0.7204]], requires_grad=True), Parameter containing:
 tensor([0.1029, 0.1811, 0.8446, 0.2938, 0.3261, 0.0145, 0.1657, 0.4143, 0.3885,
         0.3392], requires_grad=True), Parameter containing:
 tensor([[-6.1907e-01, -4.5060e-02,  1.2651e-01, -5.1144e-01, -1.1409e-01,
          -1.3749e-02,  5.8296e-01,  3.9383e-01,  4.0972e-01,  3.6461e-01],
         [ 3.4307e-01,  1.0154e-01,  4.0803e-01,  6.8925e-01,  3.5350e-01,
          -6.0197e-02, -2.8623e-01, -4.3742e-01, -1.0250e-02, -1.2318e-01],
         [ 7.1150e-01,  1.8087e-03,  4.6912e-01,  3.0792e-01,  1.6014e-01,
          -3.8484e-02, -5.9929e-01,  1.0997e-01, -3.9765e-02, -5.0214e-01],
         [-3.9248e-02, -3.4363e-01,  3.1740e-03,

In [36]:
torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()

tensor([[-0.2650, -1.7622]])

In [37]:
y_cust_40_20000=model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_40_20000

tensor([[-2.3364e-03, -6.0603e+00]], grad_fn=<LogSoftmaxBackward>)

In [39]:
_,predicted_40_20000=torch.max(y_cust_40_20000.data,-1)
predicted_40_20000

tensor([0])

In [40]:
y_cust_42_50000=model(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000

tensor([[-0.8400, -0.5652]], grad_fn=<LogSoftmaxBackward>)

In [41]:
_,predicted_42_50000=torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

tensor([1])

In [42]:
torch.save(model,'customer_buy.pt')

In [43]:
!ls

customer_buy.pt  sample_data


In [44]:
restored_model=torch.load('customer_buy.pt')

In [45]:
y_cust_40_20000=restored_model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_40_20000

tensor([[-2.3364e-03, -6.0603e+00]], grad_fn=<LogSoftmaxBackward>)

In [46]:
model.state_dict()

OrderedDict([('fc1.weight', tensor([[ 1.0988, -0.1193],
                      [-0.0057, -0.2760],
                      [ 0.5741, -0.5408],
                      [-0.6625,  0.7003],
                      [-0.5312,  0.5740],
                      [-0.7026,  0.1856],
                      [-0.5304, -0.5804],
                      [-0.6738, -0.7524],
                      [-0.7640, -0.5853],
                      [-0.3940, -0.7204]])),
             ('fc1.bias',
              tensor([0.1029, 0.1811, 0.8446, 0.2938, 0.3261, 0.0145, 0.1657, 0.4143, 0.3885,
                      0.3392])),
             ('fc2.weight',
              tensor([[-6.1907e-01, -4.5060e-02,  1.2651e-01, -5.1144e-01, -1.1409e-01,
                       -1.3749e-02,  5.8296e-01,  3.9383e-01,  4.0972e-01,  3.6461e-01],
                      [ 3.4307e-01,  1.0154e-01,  4.0803e-01,  6.8925e-01,  3.5350e-01,
                       -6.0197e-02, -2.8623e-01, -4.3742e-01, -1.0250e-02, -1.2318e-01],
                      [ 7.11

In [48]:
torch.save(model.state_dict(),'customer_buy_state_dict')

In [49]:
!ls

customer_buy.pt  customer_buy_state_dict  sample_data


In [51]:
new_predictor=Net()

In [52]:
y_cust_40_20000=new_predictor(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_40_20000

tensor([[-0.8330, -0.5705]], grad_fn=<LogSoftmaxBackward>)

In [50]:
!zip -r customer_buy_state_dict.zip customer_buy_state_dict

  adding: customer_buy_state_dict (deflated 46%)


In [53]:
!ls

customer_buy.pt		 customer_buy_state_dict.zip
customer_buy_state_dict  sample_data


In [54]:
from google.colab import files

In [55]:
files.download('customer_buy_state_dict.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>